### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by fbaiodias** [bravebunny/cops#17]
### words related to the game

Hot
^Babes
Pursuit
Cops
Fugitives
Speed
Fast
Bandit
Wheels
Rush

Rustler
Lifter
Looter
Reaver
Burglar
Cracksman
Lurcher
Outlaw
### possible names

Purrsuit
Bofya
Hot cops fast fugitives
Poolice
Mad Pursuit
Rush Pursuit
Pursuit Rush

**Comment by Raicuparta** [comment]
The Good Sambaritan: és um israelita que quer dançar o samba, mas a polícia não deixa
I Got 99 Problems But a Cop Ain't One
Pup Fiction: os polícias são cãezinhos e têm todos uma overdose
"Mr, Rob Otto!": alguém pede-te pa roubar um gajo chamado Otto
Me-Mentos: um gajo que perde a memória sempre que come um mento

**Comment by Raicuparta** [comment]
PURSUIT RUSH

**Comment by fbaiodias** [comment]
:heart: :heart:
